### PR TITLE
Revert "Upgrade to Angular 5 (#201)"

### PR DESCRIPTION
**Pull request by calbach**
Still figuring out why this was causing errors - just reverting in the meantime.

```
docker-compose -f dsub-google-compose.yml up
Recreating jobmanager_ui_1 ... 
Starting jobmanager_dsub_1 ... 
Recreating jobmanager_ui_1
Recreating jobmanager_ui_1 ... done
Recreating jobmanager_jobs-proxy_1 ... 
Recreating jobmanager_jobs-proxy_1 ... done
Attaching to jobmanager_dsub_1, jobmanager_ui_1, jobmanager_jobs-proxy_1
dsub_1        | [2018-02-07 18:45:54 +0000] [1] [INFO] Starting gunicorn 19.7.1
dsub_1        | [2018-02-07 18:45:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:8190 (1)
ui_1          | npm info it worked if it ends with ok
ui_1          | npm info using npm@5.3.0
ui_1          | npm info using node@v8.5.0
dsub_1        | [2018-02-07 18:45:54 +0000] [1] [INFO] Using worker: sync
dsub_1        | [2018-02-07 18:45:54 +0000] [11] [INFO] Booting worker with pid: 11
ui_1          | npm info lifecycle job-manager-ui@0.0.1~preng: job-manager-ui@0.0.1
ui_1          | npm info lifecycle job-manager-ui@0.0.1~ng: job-manager-ui@0.0.1
ui_1          | 
ui_1          | > job-manager-ui@0.0.1 ng /ui
ui_1          | > ng "serve" "--host" "ui" "--env=dsub_google"
ui_1          | 
ui_1          | ** NG Live Development Server is listening on ui:4200, open your browser on http://ui:4200/ **
ui_1          | Date: 2018-02-07T18:46:02.403Z
ui_1          | Hash: 5bd70bb346f5ae451fc4
ui_1          | Time: 4959ms
ui_1          | chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
ui_1          | chunk {main} main.bundle.js (main) 2.93 kB [initial] [rendered]
ui_1          | chunk {polyfills} polyfills.bundle.js (polyfills) 636 bytes [initial] [rendered]
ui_1          | chunk {styles} styles.bundle.js (styles) 183 kB [initial] [rendered]
ui_1          | chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]
ui_1          | 
ui_1          | ERROR in error TS2688: Cannot find type definition file for 'angular'.
ui_1          | 
ui_1          | 
ui_1          | webpack: Failed to compile.
```

This reverts commit 7b579c1e654342477297e96b693547a43b8f4858.

### CODE REVIEW

**Comment by alahwa** [comment]
What's the issue here?

**Comment by calbach** [comment]
Added the error I'm seeing to the description. Oddly it was working initially. Perhaps only broke due to package-lock changing on something.

**Comment by samanehsan** [comment]
Why does this cause the tests to fail?

**Comment by calbach** [comment]
Dropping in favor of https://github.com/DataBiosphere/job-manager/pull/203

**Pull request closed without merging**
