### PR TITLE
Include authuser on GCS links

### LINKED ISSUE #486: Google Auth should use the appropriate Google account for bucket links
I'm not sure of the best way to handle this, but currently if we click on a bucket link in the UI, it always uses the first user logged in in the browser, so the console UI displays a 403 if that user doesn't have access to the bucket.

When GCP console handles this in Console UI, they use `authuser=x` param in all links. I think it should be possible to use that here as well, based on the list of logged in users on the client.

### PR DESCRIPTION
**Pull request by calbach**
closes #486

### CODE REVIEW

**Comment by ruchim** [comment]
@calbach -- any update here? Thanks!

**Comment by gemmalam** [comment]
@ruchim CH messaged me on slack that he would circle back to finish this work this week.

**Comment by ruchim** [comment]
perfect!

**Comment by rsasch** [comment]
@calbach Is this change still necessary since the log links are now going to Google Console, instead of Google Storage (see #561)?

**Comment by calbach** [comment]
Yes. Cloud console will 403 if you are multilogged in and you don't have access to the bucket on your primary account. This should be the case with either Cloud Console or the direct storage URL.

**Comment by calbach** [comment]
Thanks

**Pull request merged**
